namespace Model
{
    public enum Pages
    {
        Empty,
        MessagePage,
        ConfirmationPage,
        PausePage,
        LoginPage,
        RegisterPage,
        RegisterSkillPage,
        ExplanationPage,
        ChaptersPage,
        ShoppingPage,
        SettingsPage,
        EpisodeReadyUpPage,
        EpisodePage,
        EpisodeResultPage,
        MatchLobbyPage,
        MatchCreatePage,
        MatchOverviewPage,
        MatchHistoryPage,
        MatchHistoryLeaderboardPage,
        MatchPlayingPage,
        MatchResultPage,
        MatchWaitingResultPage,
        GamemodesOverviewPage
    }
}
